name: AWS Lambda Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install AWS Cli SDK
              run: |
                  pip3 install awscli --upgrade --user
            - name: Configure AWS Account
              env:
                  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
              run: |
                  aws configure set aws_access_key_id $AWS_ACCESS_KEY
                  aws configure set aws_secret_access_key $AWS_SECRET_KEY
                  aws configure set default.region eu-central-1
                  aws configure set default.response json
            - name: Package Lambda Functions
              run: |
                  pushd AWSLambda
                  pushd atdCpuBound
                  zip -r function.zip .
                  pushd ..
                  pushd atdMemoryBound
                  zip funtion.zip index.js
            - name: Deploy & Update lambda functions
              run: |
                  aws lambda update-function-code --function-name atdCpuBound --zip-file fileb://AWSLambda/atdCpuBound/function.zip
                  aws lambda update-function-code --function-name atdMemoryBound --zip-file fileb://AWSLambda/atdMemoryBound/function.zip
